<?php

return [
    'frontend'=>[
        'menu'=>[
            [
                'icon'=>'home',
                'title'=>'Categories',
                'url'=>'/'
            ],
            [
                'icon'=>'pie-chart',
                'title'=>'Rating',
                'url'=>'/rating'
            ]
        ]
    ],
    'backend'=>[
        'menu'=>[
            [
                'icon'=>'briefcase',
                'title'=>'Categories',
                'childrens'=>[
                    [
                        'icon'=>'list',
                        'title'=>'List',
                        'url'=>'/backend/categories'
                    ],
                    [
                        'icon'=>'plus',
                        'title'=>'Create',
                        'url'=>'/backend/categories/create'
                    ]
                ]
            ],
            [
                'icon'=>'users',
                'title'=>'Users',
                'childrens'=>[
                    [
                        'icon'=>'list',
                        'title'=>'List',
                        'url'=>'/backend/users',
                    ],
                    [
                        'icon'=>'plus',
                        'title'=>'Create',
                        'url'=>'/backend/users/create',
                    ]
                ]
            ]
        ]
    ]
];
